# environment.yml
name: fault_clustering_env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pydantic=1.10.2
  - pyyaml=6.0
  - geopandas=0.12.2
  - pandas=2.0.3
  - matplotlib=3.7.1
  - shapely=2.0.1
  - scikit-learn=1.2.2
  - geopy=2.3.0
  - pyproj=3.4.2
  - folium=0.14.1
  - pygmt=0.6.4
  - pip:
    - # Add any pip-only packages here if necessary
